Update test-sync-main.yml

diff --git a/.github/workflows/test-sync-main.yml b/.github/workflows/test-sync-main.yml
--- a/.github/workflows/test-sync-main.yml
+++ b/.github/workflows/test-sync-main.yml
@@ -16,7 +16,7 @@ jobs:
      - name: Sync
        run: |
          cd $GITHUB_WORKSPACE/src
-         branch=(main)
+         branch="main"
          base_repo="git@github.com:hanzhan1/llvm.git"
          sync_repo="https://github.com/llvm/llvm-project"
          if [ ! -d ".git" ]; then
@@ -24,30 +24,28 @@ jobs:
             rm -rf ./.*
             git clone --progress $base_repo
          fi
-         for b in ${branch[*]};do
-            if [ ! -z "$(git status --porcelain)" ]; then
-                git status
-                echo "$b workspace dirty, abort"
-                return 1
-            fi
-            git checkout $b
-            git remote prune origin
-            git pull --ff --ff-only origin
-            if [ $? -ne 0 ]; then
-                echo "failed to pull from origin, abort"
-                return 1
-            fi
-            git pull --ff --ff-only $sync_repo $b
-            if [ $? -ne 0 ]; then
-                echo "failed to pull from $sync_repo $b, abort"
-                return 1
-            fi
-            if [ "equal" == "$(get_state origin/$b $b)" ] ; then
-                echo "no change, skip"
-            elif [ "ahead" == "$(get_state origin/$b $b)" ] ; then
-                git push origin
-            else
-                echo "$b branch invalid state"
-                return 1
-            fi
-         done
+         if [ ! -z "$(git status --porcelain)" ]; then
+            git status
+            echo "$b workspace dirty, abort"
+            return 1
+          fi
+          git checkout $b
+          git remote prune origin
+          git pull --ff --ff-only origin
+          if [ $? -ne 0 ]; then
+              echo "failed to pull from origin, abort"
+              return 1
+          fi
+          git pull --ff --ff-only $sync_repo $b
+          if [ $? -ne 0 ]; then
+              echo "failed to pull from $sync_repo $b, abort"
+              return 1
+          fi
+          if [ "equal" == "$(get_state origin/$b $b)" ] ; then
+              echo "no change, skip"
+          elif [ "ahead" == "$(get_state origin/$b $b)" ] ; then
+              git push origin
+          else
+              echo "$b branch invalid state"
+              return 1
+          fi
